#
# File:    handc/heapi/Makefile
#
#          Copyright (C)1997 Donovan Kolbly <d.kolbly@rosette.com>
#          as part of the RScheme project, licensed for free use
#
# Version: %I%
# Date:    %G% %U%
# Build:   %b%
#

CFILES=loadimag.c savewrit.c savetrav.c saveq.c mapf.c
PRODUCT=heapi.o

include ../postambl.mak
