#---------------------------------------------------------*-Makefile-*----#
# File:    %p%
#
#          Copyright (C)1997 Donovan Kolbly <d.kolbly@rosette.com>
#          as part of the RScheme project, licensed for free use
#
# Version: %I%
# Date:    %E% %U%
# Build:   %b%
#
# Purpose: 

CFILES=unstub.c
PRODUCT=unstb.o
include ../postambl.mak
