#
# File:    handc/dfltmain/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: %I%
# Date:    %G% %U%
# Build:   %b%
#
#

CFILES=main.c findimag.c
PRODUCT=dfltmain.o
include ../postambl.mak
