#
# File:    handc/loadboot/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: %I%
# Date:    %G% %U%
# Build:   %b%
#

CFILES=loadboot.c
PRODUCT=ldboot.o
include ../postambl.mak
