#
# File:    handc/bci/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: %I%
# Date:    %G% %U%
# Build:   %b%
#
#


CFILES=bcinterp.c
PRODUCT=bci.o
include ../postambl.mak

bcinterp.o: bcinterp.c bcfrags.ci
