#
# File:    handc/cfg/gcadapt/irc/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: %I%
# Date:    %G% %U%
# Build:   %b%
#
#

CFILES=gcclient.c
PRODUCT=gcadapt.o
include ../postambl.mak
