#!/bin/sh
#
#  Build the configuration script that is loaded by the
#  compiler to get all the configuration settings, including
#  the version of RScheme being built and the pathnames

dist_path=$1
build_id="$2"
dist_path=`cd $dist_path ; pwd`

b="${build_id}"
if test -z "$b"
then b="Dev Build, `date +'%Y-%m-%d %H:%M'`"
fi

# strip off date part and leading "v"
v=`echo "$b" | sed 's/,.*//' | sed 's/^v//'`
vlist=`echo "$b" | sed 's/[^0-9][^0-9]*/ /g'`

#
#  configure some build flags depending on what version of
#  RScheme we are running in
#

rsv=`$RS --version`

case "$rsv" in
  0.6*) sis=old ;;
  *)    sis=new ;;
esac

case "$rsv" in
  0.7.3*|Dev*)    rfp=t ;;
  *)         rfp=f ;;
esac

cat <<EOF
,(use paths)

(define *save-image-signature* '$sis)
(define *relative-file-paths* #$rfp)
(define *dist-path* (string->dir "$dist_path"))
(define *rscheme-build* "$b")
(define *rscheme-version* "$v")
(define *rscheme-build-vlist* '($vlist))
EOF

## ie, mkcfg > src/tmp/buildcfg.scm
