#
# File:    handc/cfg/gc/irc/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: %I%
# Date:    %G% %U%
# Build:   %b%
#
#


CFILES=makeheap.c gcalloc.c writebar.c ptrlist.c traverse.c
PRODUCT=xgc.o

include ../postambl.mak
